# Removed duplicate commented-out sections for clarity and consistency.
  




#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^1.0.8
#   uuid: ^3.0.7
#   web: ^1.1.1
  
# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   flutter_lints: ^5.0.0

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   # To add assets to your application, add an assets section, like this:
#   # assets:
#   #   - images/a_dot_burr.jpeg
#   #   - images/a_dot_ham.jpeg

#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/to/resolution-aware-images

#   # For details regarding adding assets from package dependencies, see
#   # https://flutter.dev/to/asset-from-package

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/to/font-from-package


name: parkingapp_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.10.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  timezone: ^0.10.0

  shared_preferences: ^2.2.2
  path_provider: ^2.0.11
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  uuid: ^3.0.7
  web: ^1.1.1

  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.0
  bloc: ^8.1.2
  provider: ^6.1.2
  equatable: ^2.0.5

  shared:
    path: ../shared
  firebase_repositories:
    path: ../firebase_repositories

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
