// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8a8Pctsi9cCg__3KnNQqDnPqH0yV5RSU',
    appId: '1:676312531060:web:2f9e5c3500e891894fd121',
    messagingSenderId: '676312531060',
    projectId: 'parkingappflutternotifications',
    authDomain: 'parkingappflutternotifications.firebaseapp.com',
    storageBucket: 'parkingappflutternotifications.firebasestorage.app',
    measurementId: 'G-1JLQHZFWYL',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8a8Pctsi9cCg__3KnNQqDnPqH0yV5RSU',
    appId: '1:676312531060:web:151a389363ed9b194fd121',
    messagingSenderId: '676312531060',
    projectId: 'parkingappflutternotifications',
    authDomain: 'parkingappflutternotifications.firebaseapp.com',
    storageBucket: 'parkingappflutternotifications.firebasestorage.app',
    measurementId: 'G-JKBEZK2HRF',
  );

}