name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  objectbox: ^4.0.3
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  equatable: ^2.0.3
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  mocktail: ^1.0.4 
  bloc: ^8.0.0
  provider: ^6.1.2
  intl: ^0.20.1  # Only one instance here
  uuid: ^3.0.4
  

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  objectbox_generator: any
  test: ^1.24.0
