// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrh3-68p0Li4kbyVKaB9xQexW_HHe7jE',
    appId: '1:26248141827:web:24660efd88162ce08a8236',
    messagingSenderId: '26248141827',
    projectId: 'parkingappflutterfirestore',
    authDomain: 'parkingappflutterfirestore.firebaseapp.com',
    storageBucket: 'parkingappflutterfirestore.firebasestorage.app',
    measurementId: 'G-2ZQLQZGDMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kYZid1Tk1nELfxQAMf0QlekJPNtN9rQ',
    appId: '1:26248141827:android:7dbe6339d6fad9968a8236',
    messagingSenderId: '26248141827',
    projectId: 'parkingappflutterfirestore',
    storageBucket: 'parkingappflutterfirestore.firebasestorage.app',
  );

}